# Configuration returned by Shopify CLI app config link on 2026-09-06.
client_id = "b314197727859b8c244255e176f8b2af"
name = "AOVBoost"
application_url = "https://ai-agent-plum-eight.vercel.app"
embedded = true
handle = "ai-agent-21"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teretret.myshopify.com"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks"
  topics = [
  "products/update",
  "app/scopes_update",
  "products/delete",
  "products/create",
  "app/uninstalled",
  "orders/create"
]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
scopes = "read_orders,read_products,write_discounts"

[auth]
redirect_urls = [
  "https://ai-agent-plum-eight.vercel.app/auth/callback",
  "https://ai-agent-plum-eight.vercel.app/auth/shopify/callback",
  "https://ai-agent-plum-eight.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://ai-agent-plum-eight.vercel.app/api"
subpath = "aovboost"
prefix = "apps"

[pos]
embedded = false
